### ISSUE TITLE
Simplified XML parsed output

### ISSUE THREAD

**Issue by christiaanwesterbeek** [timneutkens/openprovider-js#2]
With [implementing the recent CLI functionality](https://github.com/timneutkens/openprovider-js/pull/1) I've noticed that the parsed XML results into JSON with an excessive amount of arrays for single elements

![image](https://user-images.githubusercontent.com/465989/51800728-c973d980-2233-11e9-8d3b-ac46cdd7492b.png)

Also, notice the extensive JSON traversing required as a result of this. https://github.com/christiaanwesterbeek/openprovider-js/blob/80d2f9f44b3bd8d271ab1e65d7e64d5e9186b95f/run.js#L21-L38

**Comment by christiaanwesterbeek** [comment]
Related: https://stackoverflow.com/questions/20238493/xml2js-how-is-the-output

**Comment by christiaanwesterbeek** [comment]
This is fixed now and will be part of PR https://github.com/timneutkens/openprovider-js/pull/1

**Comment by timneutkens** [comment]
Hey @christiaanwesterbeek, there are actually better ways to work with XML than this library, for example combining npmjs.com/node-fetch with npmjs.com/cheerio for parsing / accessing values is way more ergonomic. Furthermore I'm not longer using openprovider (used it at my previous job) so I don't have a need for this functionality, the correct way to go would be to fork this library, however I'd highly recommend looking into using node-fetch + cheerio, that's how I'd implement this library if I'd have to implement it right now.

**Comment by christiaanwesterbeek** [comment]
Sounds like great improvements. But why is forking the correct way to go rather than improving this existing repo? This repo is linked to `npm install openprovider`. I'm happy to implement the improvements you suggested...

**Comment by timneutkens** [comment]
Because as said I'm no longer maintaining this library and it doesn't require any changes at this point. The implementation works, there's just better way to implement it (which would be breaking). The package has had exactly 0 download in the last week also.
